CREATE EXTENSION IF NOT EXISTS citext;

CREATE TABLE IF NOT EXISTS user_ (
    id_ BIGSERIAL PRIMARY KEY,
    email_ CITEXT UNIQUE NOT NULL,
    password_hash_ CHAR(60) NOT NULL,
    created_at_ TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
